name: tokonovel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_svg: ^2.0.0+1
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0
  pdf: ^3.10.1
  printing: ^5.10.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.6
  firebase_storage: ^13.0.3
  image_picker: ^1.2.0
  image: ^4.5.4
  share_plus: ^10.0.0

  # Admin Panel Dependencies
  provider: ^6.1.2
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^26.1.42
  data_table_2: ^2.5.12
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
